POST http://localhost:8080/airspaceUsers
Content-Type: application/json

< ./input/au1.json

###

GET http://localhost:8080/airspaceUsers
Accept: application/json

>> ./output/getAirspaceUser.json

###

POST http://localhost:8080/start/HungarianOptimizer/ZeroAndOutSimulator

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution1.json
>> ./output/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution1.json
>> ./output/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution1.json
>> ./output/statistic.json

###

DELETE http://localhost:8080/end

>> ./output/overview.json

###