POST http://localhost:8080/airspaceUsers
Content-Type: application/json

< ./input/au1.json

###

GET http://localhost:8080/airspaceUsers
Accept: application/json

>> ./output/getAirspaceUser.json

###

#DELETE http://localhost:8080/airspaceUsers

###

POST http://localhost:8080/start/HungarianOptimizer

###

POST http://localhost:8080/run
Content-Type: application/json

< ./input/flightDistribution1.json

###

GET http://localhost:8080/statistic/0
Content-Type: application/json

>> ./output/statistic.json

###
