# 200 cycles
# Zero And Out
# Hungerian Optimizer
# 30 min delay for each cycle
#
# Aggressive:
# "priorityFlightMinutesToAdd": [30, 50] default: [15, 45]

POST http://localhost:8080/airspaceUsers
Content-Type: application/json

< ./input/AirspaceUser.json

###

GET http://localhost:8080/airspaceUsers
Accept: application/json

>> ./output/zeroAndOut/getAirspaceUser.json

###

POST http://localhost:8080/start/HungarianOptimizer/ZeroAndOutSimulator

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

POST http://localhost:8080/run/30
Content-Type: application/json

< ./input/flightDistribution.json
>> ./output/zeroAndOut/statistic.json

###

DELETE http://localhost:8080/end

>> ./output/zeroAndOut/overview.json

###